### ISSUE TITLE
Project Ideas 🌟

### ISSUE THREAD

**Issue by mhaidarhanif** [impactbyte-haku/projects#3]
Put your Figma links and exported images here.

**Comment by yevgenysiregar** [comment]
Aplikasi semacam Ruangguru, dengan tampilan interface seperti gojek, tapi untuk non-akademik, tapi lebih untuk mempertemukan pengajar dan murid di kehidupan nyata, dan ngetrack progress murid dalam pembelajaran, dan pula dengan adanya komponen feedback yang mengefektifkan komunikasi antara murid dan pengajar.
